import{a as q,S as v,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function u(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=u(e);fetch(e.href,r)}})();const S="53646537-90648830b558eb0aebf2e1e33",$="https://pixabay.com/api/";async function h(o){const t=await q.get($,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}});return{hits:t.data.hits,totalHits:t.data.totalHits}}const c=document.querySelector(".gallery"),g=document.querySelector(".load-more"),B=new v(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(o){const t=o.map(({webformatURL:u,largeImageURL:n,tags:e,likes:r,views:s,comments:L,downloads:w})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${u}" alt="${e}" />
        </a>
        <ul class="info">
        <li><b>Likes:</b> ${r}</li>
        <li><b>Views:</b> ${s}</li>
        <li><b>Comments:</b> ${L}</li>
        <li><b>Downloads:</b> ${w}</li>
        </ul>
        </li>
        `).join("");c.insertAdjacentHTML("beforeend",t),B.refresh()}function H(){c.innerHTML=""}function p(){c.classList.add("loading")}function b(){c.classList.remove("loading")}function M(){g.hidden=!1}function f(){g.hidden=!0}const d=document.querySelector(".form"),P=document.querySelector(".load-more");let l="",i=1,m=0;d.addEventListener("submit",async o=>{if(o.preventDefault(),l=d["search-text"].value.trim(),!l){a.warning({message:"Please enter a search query",position:"topRight"});return}i=1,H(),f(),p();try{const t=await h(l,i);if(m=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),i*15<m?M():f()}catch(t){a.error({message:"Error fetching images",position:"topRight"}),console.error(t)}finally{b(),d.reset()}});P.addEventListener("click",async()=>{i+=1,p();try{const o=await h(l,i);y(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i*15>=m&&(f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){a.error({message:"Error fetching more images",position:"topRight"}),console.error(o)}finally{b()}});
//# sourceMappingURL=index.js.map
