import{a as w,S as q,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function u(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=u(e);fetch(e.href,o)}})();const v="53646537-90648830b558eb0aebf2e1e33",S="https://pixabay.com/api/";async function g(r){return(await w.get(S,{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.totalHits}const c=document.querySelector(".gallery");document.querySelector(".load-more");const B=new q(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function h(r){const t=r.map(({webformatURL:u,largeImageURL:n,tags:e,likes:o,views:s,comments:b,downloads:L})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${u}" alt="${e}" />
        </a>
        <ul class="info">
        <li><b>Likes:</b> ${o}</li>
        <li><b>Views:</b> ${s}</li>
        <li><b>Comments:</b> ${b}</li>
        <li><b>Downloads:</b> ${L}</li>
        </ul>
        </li>
        `).join("");c.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){c.innerHTML=""}function y(){c.classList.add("loading")}function p(){c.classList.remove("loading")}function P(){LoadMoreButton.hidden=!1}function f(){LoadMoreButton.hidden=!0}const d=document.querySelector(".form"),$=document.querySelector(".load-more");let l="",i=1,m=0;d.addEventListener("submit",async r=>{if(r.preventDefault(),l=d["search-text"].value.trim(),!l){a.warning({message:"Please enter a search query",position:"topRight"});return}i=1,M(),f(),y();try{const t=await g(l,i);if(m=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(t.hits),i*15<m?P():f()}catch(t){a.error({message:"Error fetching images",position:"topRight"}),console.error(t)}finally{p(),d.reset()}});$.addEventListener("click",async()=>{i+=1,y();try{const r=await g(l,i);h(r.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i*15>=m&&(f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){a.error({message:"Error fetching more images",position:"topRight"}),console.error(r)}finally{p()}});
//# sourceMappingURL=index.js.map
