import{a as $,S as B,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const M="53646537-90648830b558eb0aebf2e1e33",E="https://pixabay.com/api/",O=15;async function m(r,e=1){return(await $.get(E,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:O,page:e}})).data}const g=document.querySelector(".loader"),h=document.querySelector(".gallery"),p=document.querySelector(".load-more"),R=new B(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});function y(r){const e=r.map(({webformatURL:n,largeImageURL:l,tags:t,likes:o,views:s,comments:P,downloads:S})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${n}" alt="${t}" />
        </a>
        <ul class="info">
        <li><b>Likes:</b> ${o}</li>
        <li><b>Views:</b> ${s}</li>
        <li><b>Comments:</b> ${P}</li>
        <li><b>Downloads:</b> ${S}</li>
        </ul>
        </li>
        `).join("");h.insertAdjacentHTML("beforeend",e),R.refresh()}function x(){h.innerHTML=""}function b(){g.classList.add("is-visible")}function L(){g.classList.remove("is-visible")}function H(){p.hidden=!1}function w(){p.hidden=!0}function C(r){r.reset()}const u=document.querySelector(".form"),q=document.querySelector(".gallery"),D=document.querySelector(".load-more"),d=15;function v(r){return new Promise(e=>setTimeout(e,r))}let c="",i=1,f=0;u.addEventListener("submit",async r=>{if(r.preventDefault(),c=u["search-text"].value.trim(),!c){a.warning({message:"Please enter a search query",position:"topRight"});return}i=1,x(),w(),b();try{const e=await m(c,i);if(f=e.totalHits,e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}await v(2e3),y(e.hits,q),e.hits.length===d&&i*d<f&&H()}catch(e){a.error({message:"Error fetching images",position:"topRight"}),console.error(e)}finally{L(),C(u)}});D.addEventListener("click",async()=>{i+=1,b();try{const r=await m(c,i);await v(2e3),y(r.hits);const{height:e}=q.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),i*d>=f&&(w(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){a.error({message:"Error fetching more images",position:"topRight"}),console.error(r)}finally{L()}});
//# sourceMappingURL=index.js.map
